### PR TITLE
chore(vite.config.js): add button shortcuts to uno config and remove …

### PR DESCRIPTION
**Pull request by siljec**
…unused method

Before:
image

Now:
image

### CODE REVIEW

**Review by BalbinaK — APPROVED** [review]

**Comment by BalbinaK** [comment]
@siljec Just a thought - would it be possible to replace those examples that rely on button shortcuts with Button components? We probably should avoid using those shortcuts as they might get deprecated in a near future.

**Comment by siljec** [comment]
Ah, for sure! I didn't know we were planning on deprecating them? I thought some teams needed them? Should I still merge this PR @BalbinaK ?

**Comment by BalbinaK** [comment]
> Ah, for sure! I didn't know we were planning on deprecating them? I thought some teams needed them? 

I think those teams that can't use our Button component had issues with SSR, which may be fixed in the nearest future. Then I thought it would make sense for us to deprecate those classes and encourage the use of our components instead.

> Should I still merge this PR @BalbinaK ?
I think it would actually be nice to use our components instead. Who knows, maybe we use this documentation as a playground somewhere, and then we'd give good example on how to build things in Warp. Wdyt?

**Comment by siljec** [comment]
> I think it would actually be nice to use our components instead. Who knows, maybe we use this documentation as a playground somewhere, and then we'd give good example on how to build things in Warp. Wdyt?

Okay, sounds good, I'll close this PR then :D

**Pull request closed without merging**
